using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Xml.Linq;
using System.IO;
using System.IO.Pipes;
using System.Xml;
using System.Runtime.Remoting.Messaging;

namespace DevOps.CSVConverter
{
    public class Program {
        static int Main(string[] args) {

            var arguments = new Arguments();
            if (! arguments.Parse(args))
            {
                Console.WriteLine("Parsing input arguments failed: " +arguments.ErrorMessage );
                Console.WriteLine(Arguments.Usage);
                return -1;
                //throw new  Exception("Test runner execution failed");
            }
            try
            {
                var testCases = new TestCases();
                var xmlList = testCases.FindXMLFiles(arguments.XmlFileDirectory);
                if (xmlList.Count > 0)
                {
                    foreach (var xmlfiles in xmlList)
                    {
                        testCases.ParseResultFile(xmlfiles);
                        FileInfo outputFile = new FileInfo(arguments.OutputDirectory.FullName + "\\ConsolidatedResults.csv");
                        if (!outputFile.Directory.Exists)
                        {
                            Directory.CreateDirectory(outputFile.DirectoryName);
                        }
                        testCases.WriteIntoCsv(outputFile.FullName);

                    }
                    Console.WriteLine("The CSV FILE IS STORED IN     " + arguments.OutputDirectory.FullName + "\\ConsolidatedResults.csv");
                    return 1;
                }
                else
                {
                    Console.WriteLine("Couldnt Find The XML Files,Please Give The Correct Directory");
                    
                    return -1;
                }
               
            }
            catch(Exception e)
            {
                Console.WriteLine(e.Message);
                return -1;

            }
        }
    }
    enum TestStatus {
        Passed = 0,
        Failed  = 1,
        Aborted = 2
    }

    class TestCase {
        public string Name;
        public TestStatus Status;
        public string Duration;
        public string FailureMessage = string.Empty;
    }

    class TestCases {
        private List<TestCase> allTestCases = new List<TestCase>();
        private const string csvHeader = "Name,Status,Duration";
        private const string csvDelimiter = ",";
        public int PassedTests = 0;
        public int FailedTests = 0;

        public IReadOnlyCollection<TestCase> AllTestCases {
            get { return allTestCases; }
        }

        public IReadOnlyCollection<TestCase> UniqueTests
        {
            get { return allTestCases.Distinct().ToList(); }
        }

        public void AppendTest(TestCase testCase) {
            allTestCases.Add(testCase);
            if (testCase.Status == TestStatus.Passed) {
                PassedTests++;
            } else {
                // TODO: Tests which are not passed are considered as failed. this can be enahnced to segrated tests based a statuses further.
                FailedTests++;
            }
        }

        public void ParseResultFile(string resultFilePath) {
            // Note: This works only for the test results generated by: nunit.consolerunner v3.11.1
            // TODO: Should have a logic to find which type of input result file is provided.
            StringBuilder sb = new StringBuilder();
            //string delimit = ",";
            XDocument testResultDoc = XDocument.Load(resultFilePath);
            var testCasesActual = testResultDoc.Descendants("test-case");
            //var testCases = new TestCases();
            foreach (var testCaseActual in testCasesActual) {
                var testCase = new TestCase();
                testCase.Name = testCaseActual.Attribute("fullname").Value;
                var testResult = testCaseActual.Attribute("result").Value;
                testCase.Status = (TestStatus)Enum.Parse(typeof(TestStatus), testResult);
                if (testCase.Status != TestStatus.Passed)
                {
                    // TODO: Xpaths to be used.
                    testCase.FailureMessage =
                        testCaseActual.Element("failure").Element("message").Value;
                }
                testCase.Duration = testCaseActual.Attribute("duration").Value;

                this.AppendTest(testCase);
            }
        }

     public  List<string> FindXMLFiles(DirectoryInfo searchDirectory)
        {
            List<string> xmlFiles = new List<string>();
            foreach (var file in searchDirectory.GetFiles(("*.xml")))
            {
                xmlFiles.Add(file.FullName);
            }

            return xmlFiles;
        }

        public void WriteIntoCsv(string filePath) {
            StreamWriter csvFileWriter = new StreamWriter(filePath);
            // Write header
            csvFileWriter.WriteLine(csvHeader);

            // TODO: Dont dump error message, which contains new line characters. Which has to be pre-processed.
            foreach (var testCase in AllTestCases) {
                var testCaseInfo = new StringBuilder();
                testCaseInfo.Append(testCase.Name + csvDelimiter);
                testCaseInfo.Append(testCase.Status + csvDelimiter);
                testCaseInfo.Append(testCase.Duration + csvDelimiter);
                csvFileWriter.WriteLine(testCaseInfo.ToString());
            }
            csvFileWriter.Close();
        }
    }
   
}
